[package]
name = "proxy_rustler"
version = "0.1.0"
edition = "2021"
author = "SourMilk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "*"
tokio = { version = "1.0", features = ["full"] }
byteorder = "*"